-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `membersonlyevent_non_member_price_field_value`;
DROP TABLE IF EXISTS `membersonlyevent`;
DROP TABLE IF EXISTS `membersonlyevent_event_membership_type`;
DROP TABLE IF EXISTS `membersonlyevent_entity_price_field_value`;

SET FOREIGN_KEY_CHECKS=1;
