-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET
FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `membersonlyevent_select_price_field`;
DROP TABLE IF EXISTS `membersonlyevent`;
DROP TABLE IF EXISTS `membersonlyevent_event_membership_type`;

SET
FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * membersonlyevent
-- *
-- * Stores members-only event configurations
-- *
-- *******************************************************/
CREATE TABLE `membersonlyevent`(
    `id`                               int unsigned NOT NULL AUTO_INCREMENT,
    `event_id`                         int unsigned NOT NULL COMMENT 'Foreign key for the Event',
    `purchase_membership_button`       tinyint       DEFAULT 0 COMMENT 'Should we provide membership purchase button when access to event denied ?',
    `notice_for_access_denied`         text          DEFAULT NULL COMMENT 'Notice message to show to the user when the access to members-only event denied.',
    `purchase_membership_button_label` varchar(255)  DEFAULT NULL COMMENT 'Purchase membership button label if it is enabled',
    `purchase_membership_link_type`    int           DEFAULT 0 COMMENT '0: contribution page, 1: custom URL',
    `contribution_page_id`             int unsigned DEFAULT NULL COMMENT 'Foreign key for the Contribution page',
    `purchase_membership_url`          varchar(3000) DEFAULT NULL COMMENT 'Purchase membership page URL',
    PRIMARY KEY (`id`),
    CONSTRAINT FK_membersonlyevent_event_id FOREIGN KEY (`event_id`) REFERENCES `civicrm_event` (`id`) ON DELETE CASCADE,
    CONSTRAINT FK_membersonlyevent_contribution_page_id FOREIGN KEY (`contribution_page_id`) REFERENCES `civicrm_contribution_page` (`id`) ON DELETE SET NULL
);

-- /*******************************************************
-- *
-- * membersonlyevent_event_membership_type
-- *
-- * Joining table for members-only event and allowed membership types
-- *
-- *******************************************************/
CREATE TABLE `membersonlyevent_event_membership_type`(
    `members_only_event_id` int unsigned NOT NULL COMMENT 'Members-only event ID.',
    `membership_type_id`    int unsigned NOT NULL COMMENT 'Allowed Membership Type ID.',
    INDEX                   `index_event_id_membership_type_id`( members_only_event_id
        , membership_type_id
        ),
    CONSTRAINT FK_membersonlyevent_event_membership_type_members_only_event_id FOREIGN KEY (`members_only_event_id`) REFERENCES `membersonlyevent` (`id`) ON DELETE CASCADE,
    CONSTRAINT FK_membersonlyevent_event_membership_type_membership_type_id FOREIGN KEY (`membership_type_id`) REFERENCES `civicrm_membership_type` (`id`) ON DELETE CASCADE
);


-- /*******************************************************
-- *
-- * membersonlyevent_select_price_field
-- *
-- * Join table for storing selected price field for members only event
-- *
-- *******************************************************/
CREATE TABLE `membersonlyevent_select_price_field`(
    `members_only_event_id` int unsigned NOT NULL COMMENT 'Members-only event ID.',
    `price_field_id`        int unsigned NOT NULL COMMENT 'Selected Price Field ID.',
    CONSTRAINT FK_membersonlyevent_select_price_field_members_only_event_id FOREIGN KEY (`members_only_event_id`) REFERENCES `membersonlyevent` (`id`) ON DELETE CASCADE,
    CONSTRAINT FK_membersonlyevent_select_price_field_price_field_id FOREIGN KEY (`price_field_id`) REFERENCES `civicrm_price_field` (`id`) ON DELETE CASCADE
);

